services:
  identity-db:
    image: postgres:16
    environment:
      POSTGRES_DB: identity_db
      POSTGRES_USER: umbral
      POSTGRES_PASSWORD: umbral
    ports:
      - "5433:5432"

  team-db:
    image: postgres:16
    environment:
      POSTGRES_DB: team_db
      POSTGRES_USER: umbral
      POSTGRES_PASSWORD: umbral
    ports:
      - "5434:5432"

  trivia-db:
    image: postgres:16
    environment:
      POSTGRES_DB: trivia_db
      POSTGRES_USER: umbral
      POSTGRES_PASSWORD: umbral
    ports:
      - "5435:5432"

  treasure-hunt-db:
    image: postgres:16
    environment:
      POSTGRES_DB: treasure_hunt_db
      POSTGRES_USER: umbral
      POSTGRES_PASSWORD: umbral
    ports:
      - "5436:5432"

  scoring-db:
    image: postgres:16
    environment:
      POSTGRES_DB: scoring_db
      POSTGRES_USER: umbral
      POSTGRES_PASSWORD: umbral
    ports:
      - "5437:5432"

  audit-db:
    image: postgres:16
    environment:
      POSTGRES_DB: audit_db
      POSTGRES_USER: umbral
      POSTGRES_PASSWORD: umbral
    ports:
      - "5438:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
