// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Umbral.Partidas.Infrastructure.Persistence;

#nullable disable

namespace Umbral.Partidas.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PartidasDbContext))]
    [Migration("20260717190931_AddOrdenAPreguntaYOpcion")]
    partial class AddOrdenAPreguntaYOpcion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Umbral.Partidas.Domain.Entities.EtapaBDT", b =>
                {
                    b.Property<Guid>("EtapaBDTId")
                        .HasColumnType("uuid")
                        .HasColumnName("etapabdtid");

                    b.Property<string>("CodigoQREsperado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigoqr");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("PuntajeAsignado")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje");

                    b.Property<int>("TiempoLimiteSegundos")
                        .HasColumnType("integer")
                        .HasColumnName("tiempolimite");

                    b.Property<Guid>("juegoid")
                        .HasColumnType("uuid");

                    b.HasKey("EtapaBDTId");

                    b.HasIndex("juegoid");

                    b.ToTable("etapas_bdt", (string)null);
                });

            modelBuilder.Entity("Umbral.Partidas.Domain.Entities.JuegoBDT", b =>
                {
                    b.Property<Guid>("JuegoId")
                        .HasColumnType("uuid")
                        .HasColumnName("juegoid");

                    b.Property<string>("AreaBusqueda")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("areabusqueda");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partidaid");

                    b.HasKey("JuegoId");

                    b.HasIndex("PartidaId")
                        .HasDatabaseName("ix_juegos_bdt_partidaid");

                    b.ToTable("juegos_bdt", (string)null);
                });

            modelBuilder.Entity("Umbral.Partidas.Domain.Entities.JuegoReferencia", b =>
                {
                    b.Property<Guid>("JuegoId")
                        .HasColumnType("uuid")
                        .HasColumnName("juegoid");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("TipoJuego")
                        .HasColumnType("integer")
                        .HasColumnName("tipojuego");

                    b.Property<Guid>("partidaid")
                        .HasColumnType("uuid");

                    b.HasKey("JuegoId");

                    b.HasIndex("partidaid");

                    b.ToTable("partida_juegos", (string)null);
                });

            modelBuilder.Entity("Umbral.Partidas.Domain.Entities.JuegoTrivia", b =>
                {
                    b.Property<Guid>("JuegoId")
                        .HasColumnType("uuid")
                        .HasColumnName("juegoid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partidaid");

                    b.HasKey("JuegoId");

                    b.HasIndex("PartidaId")
                        .HasDatabaseName("ix_juegos_trivia_partidaid");

                    b.ToTable("juegos_trivia", (string)null);
                });

            modelBuilder.Entity("Umbral.Partidas.Domain.Entities.Opcion", b =>
                {
                    b.Property<Guid>("OpcionId")
                        .HasColumnType("uuid")
                        .HasColumnName("opcionid");

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("boolean")
                        .HasColumnName("escorrecta");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.Property<Guid>("preguntaid")
                        .HasColumnType("uuid");

                    b.HasKey("OpcionId");

                    b.HasIndex("preguntaid");

                    b.ToTable("opciones", (string)null);
                });

            modelBuilder.Entity("Umbral.Partidas.Domain.Entities.Partida", b =>
                {
                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partidaid");

                    b.Property<int?>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechacreacion");

                    b.Property<int>("MaximosParticipacion")
                        .HasColumnType("integer")
                        .HasColumnName("maximos");

                    b.Property<int>("MinimosParticipacion")
                        .HasColumnType("integer")
                        .HasColumnName("minimos");

                    b.Property<int>("Modalidad")
                        .HasColumnType("integer")
                        .HasColumnName("modalidad");

                    b.Property<int>("ModoInicioPartida")
                        .HasColumnType("integer")
                        .HasColumnName("modoinicio");

                    b.Property<string>("NombrePartida")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombrepartida");

                    b.Property<DateTime?>("TiempoInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tiempoinicio");

                    b.HasKey("PartidaId");

                    b.ToTable("partidas", (string)null);
                });

            modelBuilder.Entity("Umbral.Partidas.Domain.Entities.Pregunta", b =>
                {
                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("uuid")
                        .HasColumnName("preguntaid");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("PuntajeAsignado")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.Property<int>("TiempoLimiteSegundos")
                        .HasColumnType("integer")
                        .HasColumnName("tiempolimite");

                    b.Property<Guid>("juegoid")
                        .HasColumnType("uuid");

                    b.HasKey("PreguntaId");

                    b.HasIndex("juegoid");

                    b.ToTable("preguntas", (string)null);
                });

            modelBuilder.Entity("Umbral.Partidas.Domain.Entities.EtapaBDT", b =>
                {
                    b.HasOne("Umbral.Partidas.Domain.Entities.JuegoBDT", null)
                        .WithMany("Etapas")
                        .HasForeignKey("juegoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Umbral.Partidas.Domain.Entities.JuegoReferencia", b =>
                {
                    b.HasOne("Umbral.Partidas.Domain.Entities.Partida", null)
                        .WithMany("Juegos")
                        .HasForeignKey("partidaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Umbral.Partidas.Domain.Entities.Opcion", b =>
                {
                    b.HasOne("Umbral.Partidas.Domain.Entities.Pregunta", null)
                        .WithMany("Opciones")
                        .HasForeignKey("preguntaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Umbral.Partidas.Domain.Entities.Pregunta", b =>
                {
                    b.HasOne("Umbral.Partidas.Domain.Entities.JuegoTrivia", null)
                        .WithMany("Preguntas")
                        .HasForeignKey("juegoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Umbral.Partidas.Domain.Entities.JuegoBDT", b =>
                {
                    b.Navigation("Etapas");
                });

            modelBuilder.Entity("Umbral.Partidas.Domain.Entities.JuegoTrivia", b =>
                {
                    b.Navigation("Preguntas");
                });

            modelBuilder.Entity("Umbral.Partidas.Domain.Entities.Partida", b =>
                {
                    b.Navigation("Juegos");
                });

            modelBuilder.Entity("Umbral.Partidas.Domain.Entities.Pregunta", b =>
                {
                    b.Navigation("Opciones");
                });
#pragma warning restore 612, 618
        }
    }
}
