// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Umbral.TriviaGame.Infrastructure.Data;

#nullable disable

namespace Umbral.TriviaGame.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TriviaGameDbContext))]
    [Migration("20260531192404_AddTriviaInscripcion")]
    partial class AddTriviaInscripcion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Umbral.TriviaGame.Domain.Entities.PartidaTrivia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByOperatorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("FormularioAsociadoId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MaximoEquipos")
                        .HasColumnType("integer");

                    b.Property<int?>("MaximoJugadores")
                        .HasColumnType("integer");

                    b.Property<int?>("MaximoJugadoresPorEquipo")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimoJugadoresPorEquipo")
                        .HasColumnType("integer");

                    b.Property<int>("MinimoParticipantes")
                        .HasColumnType("integer");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ModoInicio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("TiempoInicio")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("partidas_trivia", (string)null);
                });

            modelBuilder.Entity("Umbral.TriviaGame.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AssignedScore")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("integer")
                        .HasColumnName("TimeLimitSeconds");

                    b.Property<Guid?>("TriviaFormId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TriviaFormId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("Umbral.TriviaGame.Domain.Entities.TriviaForm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByOperatorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TriviaForms", (string)null);
                });

            modelBuilder.Entity("Umbral.TriviaGame.Domain.Entities.TriviaInscripcion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("trivia_inscripciones", (string)null);
                });

            modelBuilder.Entity("Umbral.TriviaGame.Domain.Entities.Question", b =>
                {
                    b.HasOne("Umbral.TriviaGame.Domain.Entities.TriviaForm", null)
                        .WithMany("Questions")
                        .HasForeignKey("TriviaFormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsMany("Umbral.TriviaGame.Domain.ValueObjects.AnswerOption", "Options", b1 =>
                        {
                            b1.Property<Guid>("QuestionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<bool>("IsCorrect")
                                .HasColumnType("boolean");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.HasKey("QuestionId", "Id");

                            b1.ToTable("QuestionOptions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("QuestionId");
                        });

                    b.Navigation("Options");
                });

            modelBuilder.Entity("Umbral.TriviaGame.Domain.Entities.TriviaForm", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
