// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Umbral.Puntuaciones.Infrastructure.Persistence;

#nullable disable

namespace Umbral.Puntuaciones.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PuntuacionesDbContext))]
    [Migration("20260706222003_SP4dHistorial")]
    partial class SP4dHistorial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Umbral.Puntuaciones.Domain.Entities.EventoHistorial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DetalleJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<Guid?>("EquipoId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipoid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("eventid");

                    b.Property<Guid?>("JuegoId")
                        .HasColumnType("uuid")
                        .HasColumnName("juegoid");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurredat");

                    b.Property<Guid?>("ParticipanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("participanteid");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partidaid");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tipoevento");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_eventos_historial_eventid");

                    b.HasIndex("PartidaId", "OccurredAt")
                        .HasDatabaseName("ix_eventos_historial_partidaid_occurredat");

                    b.ToTable("eventos_historial", (string)null);
                });

            modelBuilder.Entity("Umbral.Puntuaciones.Domain.Entities.EventoProcesado", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("eventid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("eventtype");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurredat");

                    b.Property<DateTime>("ProcesadoAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("procesadoat");

                    b.HasKey("EventId");

                    b.HasIndex("ProcesadoAt")
                        .HasDatabaseName("ix_eventos_procesados_procesadoat");

                    b.ToTable("eventos_procesados", (string)null);
                });

            modelBuilder.Entity("Umbral.Puntuaciones.Domain.Entities.JuegoProyectado", b =>
                {
                    b.Property<Guid>("JuegoId")
                        .HasColumnType("uuid")
                        .HasColumnName("juegoid");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partidaid");

                    b.Property<int>("TipoJuego")
                        .HasColumnType("integer")
                        .HasColumnName("tipojuego");

                    b.HasKey("JuegoId");

                    b.HasIndex("PartidaId")
                        .HasDatabaseName("ix_juegos_proyectados_partidaid");

                    b.ToTable("juegos_proyectados", (string)null);
                });

            modelBuilder.Entity("Umbral.Puntuaciones.Domain.Entities.Marcador", b =>
                {
                    b.Property<Guid>("JuegoId")
                        .HasColumnType("uuid")
                        .HasColumnName("juegoid");

                    b.Property<Guid>("CompetidorId")
                        .HasColumnType("uuid")
                        .HasColumnName("competidorid");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partidaid");

                    b.Property<int>("PuntosAcumulados")
                        .HasColumnType("integer")
                        .HasColumnName("puntosacumulados");

                    b.Property<long>("TiempoAcumuladoMs")
                        .HasColumnType("bigint")
                        .HasColumnName("tiempoacumuladoms");

                    b.Property<int>("TipoCompetidor")
                        .HasColumnType("integer")
                        .HasColumnName("tipocompetidor");

                    b.Property<int>("UnidadesGanadas")
                        .HasColumnType("integer")
                        .HasColumnName("unidadesganadas");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("JuegoId", "CompetidorId");

                    b.HasIndex("JuegoId")
                        .HasDatabaseName("ix_marcadores_juegoid");

                    b.ToTable("marcadores", (string)null);
                });

            modelBuilder.Entity("Umbral.Puntuaciones.Domain.Entities.PartidaProyectada", b =>
                {
                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partidaid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechafin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechainicio");

                    b.Property<int?>("Modalidad")
                        .HasColumnType("integer")
                        .HasColumnName("modalidad");

                    b.Property<Guid>("SesionPartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesionpartidaid");

                    b.HasKey("PartidaId");

                    b.ToTable("partidas_proyectadas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
