// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Umbral.OperacionesSesion.Infrastructure.Persistence;

#nullable disable

namespace Umbral.OperacionesSesion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OperacionesSesionDbContext))]
    [Migration("20260630031313_SP3f1ConcurrencyToken")]
    partial class SP3f1ConcurrencyToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.EtapaSnapshot", b =>
                {
                    b.Property<Guid>("EtapaId")
                        .HasColumnType("uuid")
                        .HasColumnName("etapaid");

                    b.Property<string>("CodigoQREsperado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigoqresperado");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estadoetapa");

                    b.Property<DateTime?>("FechaActivacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaactivacion");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechacierre");

                    b.Property<Guid?>("GanadorParticipanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ganadorparticipanteid");

                    b.Property<int?>("MotivoCierre")
                        .HasColumnType("integer")
                        .HasColumnName("motivocierre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("Puntaje")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje");

                    b.Property<int>("TiempoLimiteSegundos")
                        .HasColumnType("integer")
                        .HasColumnName("tiempolimitesegundos");

                    b.Property<long?>("TiempoResolucionMs")
                        .HasColumnType("bigint")
                        .HasColumnName("tiemporesolucionms");

                    b.Property<Guid>("juegoid")
                        .HasColumnType("uuid");

                    b.HasKey("EtapaId");

                    b.HasIndex("juegoid");

                    b.ToTable("etapas_snapshot", (string)null);
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.InscripcionPartida", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechainscripcion");

                    b.Property<Guid>("ParticipanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("participanteid");

                    b.Property<Guid>("sesionid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("sesionid");

                    b.ToTable("inscripciones", (string)null);
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.JuegoResumen", b =>
                {
                    b.Property<Guid>("JuegoId")
                        .HasColumnType("uuid")
                        .HasColumnName("juegoid");

                    b.Property<string>("AreaBusqueda")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("areabusqueda");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estadojuego");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("TipoJuego")
                        .HasColumnType("integer")
                        .HasColumnName("tipojuego");

                    b.Property<Guid>("sesionid")
                        .HasColumnType("uuid");

                    b.HasKey("JuegoId");

                    b.HasIndex("sesionid");

                    b.ToTable("sesion_juegos", (string)null);
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.OpcionSnapshot", b =>
                {
                    b.Property<Guid>("OpcionId")
                        .HasColumnType("uuid")
                        .HasColumnName("opcionid");

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("boolean")
                        .HasColumnName("escorrecta");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.Property<Guid>("preguntaid")
                        .HasColumnType("uuid");

                    b.HasKey("OpcionId");

                    b.HasIndex("preguntaid");

                    b.ToTable("opciones_snapshot", (string)null);
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.PreguntaSnapshot", b =>
                {
                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("uuid")
                        .HasColumnName("preguntaid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estadopregunta");

                    b.Property<DateTime?>("FechaActivacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaactivacion");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechacierre");

                    b.Property<Guid?>("GanadorParticipanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ganadorparticipanteid");

                    b.Property<int?>("MotivoCierre")
                        .HasColumnType("integer")
                        .HasColumnName("motivocierre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("PuntajeAsignado")
                        .HasColumnType("integer")
                        .HasColumnName("puntajeasignado");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.Property<int>("TiempoLimiteSegundos")
                        .HasColumnType("integer")
                        .HasColumnName("tiempolimitesegundos");

                    b.Property<Guid>("juegoid")
                        .HasColumnType("uuid");

                    b.HasKey("PreguntaId");

                    b.HasIndex("juegoid");

                    b.ToTable("preguntas_snapshot", (string)null);
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.RespuestaTrivia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("boolean")
                        .HasColumnName("escorrecta");

                    b.Property<DateTime>("Instante")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instante");

                    b.Property<Guid>("OpcionId")
                        .HasColumnType("uuid")
                        .HasColumnName("opcionid");

                    b.Property<Guid>("ParticipanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("participanteid");

                    b.Property<Guid>("preguntaid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("preguntaid");

                    b.ToTable("respuestas_trivia", (string)null);
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.SesionPartida", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechafin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechainicio");

                    b.Property<int>("MaximosParticipacion")
                        .HasColumnType("integer")
                        .HasColumnName("maximos");

                    b.Property<int>("MinimosParticipacion")
                        .HasColumnType("integer")
                        .HasColumnName("minimos");

                    b.Property<int>("Modalidad")
                        .HasColumnType("integer")
                        .HasColumnName("modalidad");

                    b.Property<int>("ModoInicioPartida")
                        .HasColumnType("integer")
                        .HasColumnName("modoinicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partidaid");

                    b.Property<DateTime?>("TiempoInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tiempoinicio");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId")
                        .IsUnique()
                        .HasDatabaseName("ix_sesiones_partidaid");

                    b.ToTable("sesiones_partida", (string)null);
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.TesoroQR", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaenvio");

                    b.Property<Guid>("ParticipanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("participanteid");

                    b.Property<string>("QrDecodificado")
                        .HasColumnType("text")
                        .HasColumnName("qrdecodificado");

                    b.Property<int>("Resultado")
                        .HasColumnType("integer")
                        .HasColumnName("resultado");

                    b.Property<Guid>("etapaid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("etapaid");

                    b.ToTable("tesoros_qr", (string)null);
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.EtapaSnapshot", b =>
                {
                    b.HasOne("Umbral.OperacionesSesion.Domain.Entities.JuegoResumen", null)
                        .WithMany("Etapas")
                        .HasForeignKey("juegoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.InscripcionPartida", b =>
                {
                    b.HasOne("Umbral.OperacionesSesion.Domain.Entities.SesionPartida", null)
                        .WithMany("Inscripciones")
                        .HasForeignKey("sesionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.JuegoResumen", b =>
                {
                    b.HasOne("Umbral.OperacionesSesion.Domain.Entities.SesionPartida", null)
                        .WithMany("Juegos")
                        .HasForeignKey("sesionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.OpcionSnapshot", b =>
                {
                    b.HasOne("Umbral.OperacionesSesion.Domain.Entities.PreguntaSnapshot", null)
                        .WithMany("Opciones")
                        .HasForeignKey("preguntaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.PreguntaSnapshot", b =>
                {
                    b.HasOne("Umbral.OperacionesSesion.Domain.Entities.JuegoResumen", null)
                        .WithMany("Preguntas")
                        .HasForeignKey("juegoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.RespuestaTrivia", b =>
                {
                    b.HasOne("Umbral.OperacionesSesion.Domain.Entities.PreguntaSnapshot", null)
                        .WithMany("Respuestas")
                        .HasForeignKey("preguntaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.TesoroQR", b =>
                {
                    b.HasOne("Umbral.OperacionesSesion.Domain.Entities.EtapaSnapshot", null)
                        .WithMany("Tesoros")
                        .HasForeignKey("etapaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.EtapaSnapshot", b =>
                {
                    b.Navigation("Tesoros");
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.JuegoResumen", b =>
                {
                    b.Navigation("Etapas");

                    b.Navigation("Preguntas");
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.PreguntaSnapshot", b =>
                {
                    b.Navigation("Opciones");

                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.SesionPartida", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("Juegos");
                });
#pragma warning restore 612, 618
        }
    }
}
