// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Umbral.OperacionesSesion.Infrastructure.Persistence;

#nullable disable

namespace Umbral.OperacionesSesion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OperacionesSesionDbContext))]
    [Migration("20260626170733_InitialOperacionesSesionModel")]
    partial class InitialOperacionesSesionModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.InscripcionPartida", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechainscripcion");

                    b.Property<Guid>("ParticipanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("participanteid");

                    b.Property<Guid>("sesionid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("sesionid");

                    b.ToTable("inscripciones", (string)null);
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.JuegoResumen", b =>
                {
                    b.Property<Guid>("JuegoId")
                        .HasColumnType("uuid")
                        .HasColumnName("juegoid");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("TipoJuego")
                        .HasColumnType("integer")
                        .HasColumnName("tipojuego");

                    b.Property<Guid>("sesionid")
                        .HasColumnType("uuid");

                    b.HasKey("JuegoId");

                    b.HasIndex("sesionid");

                    b.ToTable("sesion_juegos", (string)null);
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.SesionPartida", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<int>("MaximosParticipacion")
                        .HasColumnType("integer")
                        .HasColumnName("maximos");

                    b.Property<int>("MinimosParticipacion")
                        .HasColumnType("integer")
                        .HasColumnName("minimos");

                    b.Property<int>("Modalidad")
                        .HasColumnType("integer")
                        .HasColumnName("modalidad");

                    b.Property<int>("ModoInicioPartida")
                        .HasColumnType("integer")
                        .HasColumnName("modoinicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partidaid");

                    b.Property<DateTime?>("TiempoInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tiempoinicio");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId")
                        .IsUnique()
                        .HasDatabaseName("ix_sesiones_partidaid");

                    b.ToTable("sesiones_partida", (string)null);
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.InscripcionPartida", b =>
                {
                    b.HasOne("Umbral.OperacionesSesion.Domain.Entities.SesionPartida", null)
                        .WithMany("Inscripciones")
                        .HasForeignKey("sesionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.JuegoResumen", b =>
                {
                    b.HasOne("Umbral.OperacionesSesion.Domain.Entities.SesionPartida", null)
                        .WithMany("Juegos")
                        .HasForeignKey("sesionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Umbral.OperacionesSesion.Domain.Entities.SesionPartida", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("Juegos");
                });
#pragma warning restore 612, 618
        }
    }
}
